FROM node:latest

RUN apt-get update && apt-get install -y fish

WORKDIR /app

COPY frontend/ frontend/

WORKDIR /app/frontend

RUN yarn install

EXPOSE 3000

SHELL ["fish", "-c"]

CMD ["yarn", "start"]

# docker build -t frontend_test .
# docker run -p 3000:3000 frontend_test
